### ISSUE TITLE
coin opreturn

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#115]
Out of curiosity I've also tested `coin opreturn 48656c6c6f20576f726c64`, where `48656c6c6f20576f726c64` is the hex representation of "Hello World" and got `068a134850a74bd593c0726999d4911cb326817cd69c2190b72fb19b327dd509` as output 
However if I run `slimcoind getrawtransaction 068a134850a74bd593c0726999d4911cb326817cd69c2190b72fb19b327dd509` locally I'm getting `error: {"code":-5,"message":"No information available about transaction"}`.
Does it mean that the `coin opreturn` command doesn't work correctly or the output is not a transaction id?

**Comment by buhtignew** [comment]
I've run `coin opreturn 48656c6c6f20576f726c64` as above, which has created transaction `2f2f66c539c3e2679ed748db782e8326ca0fe5b02bdfabaf391e165fc1357008`.

Then I've run `slimcoind getrawtransaction 2f2f66c539c3e2679ed748db782e8326ca0fe5b02bdfabaf391e165fc1357008` and got:
```
01000000b923a8680181a52458d3a9ad888b4e9855c96196e95caa6356d6c234b54c7b2f831dd9de2b010000006b483045022100dd6e054accf33ebc406699faf171a4592d989436eb4e0b6bb2b9559354349895022023585cf683d9aab6d1e8694ba25383d0d189c227a47dd61614e66a4cad17b9b60121024538afb5b36bf1d8dc04d9903d0eed638b153cca261ece0d3b2c026e56da97dfffffffff0210270000000000000d6a0b48656c6c6f20576f726c6400b77906000000001976a9148647d52e3e01ad837cf34c615d6f26e5f05e40bb88ac00000000
``` 
which contains the original string `48656c6c6f20576f726c64`.

Then I've run `transaction show 2f2f66c539c3e2679ed748db782e8326ca0fe5b02bdfabaf391e165fc1357008 -s` and got:
```

    'inputs': [
        {'sender': ['mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35'], 'value': 108.66}
    ],
    'outputs': [
        {'receivers': [], 'value': 0.01},
        {'receivers': ['mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35'], 'value': 108.64}
    ],
    'blockheight': 843925
}
```
So it seems to work, if I've got it right I've published the hex representation of "Hello world" on blockchain.

I'm tempted to ask whether there is a tool to read just hex string, knowing the transaction id, but I'm afraid to drag us into another rabbit hole, TBH.

Feel free to close.

**Comment by buhtignew** [comment]
> Done.

I've run ` coin opreturn Hello_world` and got:
```
  File "~/.local/lib/python3.13/site-packages/pacli/coin.py", line 124, in __opreturn
    op_return_script = nulldata_script(bytes.fromhex(str(string)))
                                       ~~~~~~~~~~~~~^^^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/pacli", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "~/.local/lib/python3.13/site-packages/pacli/__main__.py", line 494, in main
    fire.Fire({
    ~~~~~~~~~^^
        'config': Config(),
        ^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
        'checkpoint' : Checkpoint()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        })
        ^^
  File "~/.local/lib/python3.13/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "~/.local/lib/python3.13/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ~~~~~~~~~~~~~~~~~~~^
        component,
        ^^^^^^^^^^
    ...<2 lines>...
        treatment='class' if is_class else 'routine',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        target=component.__name__)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.13/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "~/.local/lib/python3.13/site-packages/pacli/coin.py", line 105, in opreturn
    return run_command(self.__opreturn, string, locktime, ascii=ascii, debug=True)
  File "~/.local/lib/python3.13/site-packages/pacli/extended_handling.py", line 32, in run_command
    result = c(*args, **kwargs)
  File "~/.local/lib/python3.13/site-packages/pacli/coin.py", line 126, in __opreturn
    raise PacliDataError("String contains invalid characters.")
pacli.extended_handling.PacliDataError: String contains invalid characters.
```
The same for the command with the long string, `coin opreturn aa4c6f72656d20697073756d20646f6c6f722073697420616d65742c20636f6e73656374657475722061646970697363696e6720656c69742e20536564206d6178696d7573206e756c6c61207175697320697073756d2066617563696275732c20766974616520756c6c616d636f72706572206c616375732074696e636964756e742e2044756973206c6163696e696120616e7465206c6967756c612c20766974616520677261766964612073656d20636f6d6d6f646f207365642e20446f6e6563207665686963756c61207075727573206d617373612c2073697420616d6574206d6f6c6573746965206e6571756520656c656966656e642061742e2050686173656c6c7573206d6f6c6573746965206c6163696e6961206d6f6c65737469652e204d6f72626920696e206c6563747573207574206f7263692072757472756d206665726d656e74756d2e2050726f696e2072757472756d20696d7065726469657420656c656966656e642e2044756973207475727069732073617069656e2c206d616c6573756164612071756973206d692076697461652c2076656e656e61746973206672696e67696c6c6120657261742eaa446f6e65632074696e636964756e742c20726973757320657420636f6e76616c6c6973206c616f726565742c2065782070757275732074656d706f72206c6967756c612c2076656c20636f6e64696d656e74756d20617567756520747572706973206e65632076656c69742e20416c697175616d206f726e61726520626962656e64756d206c6f72656d207365642074696e636964756e742e205072616573656e7420766573746962756c756d2074656d707573206d61737361206174207661726975732e204e756c6c616d20757420636f6e7365717561742065782e2053656420616c69717565742c206c696265726f2073697420616d65742076756c70757461746520666575676961742c20656c697420616e7465207068617265747261206c616375732c20616320656c656d656e74756d206f64696f20697073756d2073697420616d6574206573742e204e756c6c616d206665726d656e74756d2065676574206e65717565206174206566666963697475722e2050656c6c656e74657371756520696163756c69732c20656e696d2076697461652066696e696275732073656d7065722c206e69736c20657820636f6e67756520646f6c6f722c206574206672696e67696c6c6120647569206d65747573206e6563206d61676e612e205175697371756520746f72746f72206c6f72656d2c20766573746962756c756d20696e20677261766964612076656c2c206c6f626f727469732061206d657475732e20566976616d75732066696e69627573206c616375732073656d2c20617420756c747269636573206e6962682074696e636964756e742075742eaa53656420617563746f7220626c616e64697420677261766964612e20496e20696420656c656d656e74756d206e69736c2e20437572616269747572207375736369706974206e756c6c61206964206f72636920646170696275732c2073697420616d657420706f7274612064756920696163756c69732e204d6f72626920766f6c75747061742074656d706f7220677261766964612e204e756c6c616d2076656c206f7263692074656d7075732c206c6163696e69612074757270697320616c69717565742c20656c656d656e74756d206f64696f2e204d6f726269207072657469756d206469616d207669746165206c696265726f2068656e6472657269742c206964207072657469756d2066656c697320616c69717565742e20496e20636f6e677565206d6f6c6c6973206d61737361206e6f6e206665726d656e74756d2e204e756c6c616d20657520726973757320677261766964612073656d20656c656966656e6420617563746f722e204d616563656e6173206469676e697373696d20656765737461732072757472756d2eaa496e206c656f2072697375732c20657569736d6f6420617420636f6e64696d656e74756d20617563746f722c206672696e67696c6c612065742070757275732e2041656e65616e20736564206c6f72656d207072657469756d206d6173736120666163696c697369732063757273757320656765742065676574206573742e2053656420696d7065726469657420746f72746f7220696e20617563746f7220626c616e6469742e2050686173656c6c75732075742074656d706f722075726e612e20496e746567657220706f72746120766573746962756c756d2076656e656e617469732e204e756c6c616d20696e20626962656e64756d2074656c6c75732c2073697420616d65742064617069627573206e6962682e2053757370656e6469737365206567657420656e696d206d6f6c6c69732c20636f6e7365637465747572206c61637573206e6f6e2c2072686f6e637573206c616375732e204e756c6c616d2065676574206d6f6c6c697320616e74652e205365642061632066696e69627573206f7263692e20566976616d75732076656e656e6174697320646f6c6f722073697420616d6574206c6163757320616363756d73616e206672696e67696c6c612e204c6f72656d20697073756d20646f6c6f722073697420616d65742c20636f6e73656374657475722061646970697363696e6720656c69742e2041656e65616e20617563746f72206c6163757320736564206c6967756c6120666175636962757320756c7472696365732e20566976616d757320706c616365726174206e657175652072697375732c206574206f726e617265206d61676e6120696d706572646965742075742e20496e2076656c20656e696d206574206e6571756520696163756c69732066617563696275732e2050656c6c656e746573717565207068617265747261206d617373612073656d2c20612076656e656e6174697320616e74652064696374756d2076697461652eaa566976616d75732076656e656e617469732c2073656d206e6f6e206c6f626f72746973206c616f726565742c206e756e632065737420766f6c7574706174206469616d2c2064617069627573207363656c65726973717565206c6563747573206469616d20656765742065782e2051756973717565206e6f6e20697073756d206574206d6173736120656c656d656e74756d20706f72747469746f722e2050726f696e20636f6e76616c6c69732073656d7065722066696e696275732e205072616573656e7420616c6971756574206d61676e6120696420697073756d2073616769747469732074696e636964756e742e20457469616d20706f73756572652c207475727069732065676574206566666963697475722074696e636964756e742c206d657475732074656c6c757320756c74726963696573206a7573746f2c2070756c76696e617220656c656966656e64206d61676e61206d692071756973206d617373612e2053656420766f6c75747061742076656c6974206d6f6c6c69732c20616c697175616d206c616375732076697461652c206d6178696d7573206c6967756c612e20496e20666175636962757320636f6e6775652061756775652c20617420656c656d656e74756d206e756e63207665686963756c61207365642e2050656c6c656e74657371756520756c74726963696573206572617420766974616520646f6c6f7220706f7274612c20696e20626962656e64756d2065737420656c656d656e74756d2e20416c697175616d20717569732070756c76696e617220646f6c6f722e20467573636520616363756d73616e20617567756520766f6c75747061742c206d6178696d7573206f72636920656765742c20736f6c6c696369747564696e206c6f72656d2e205365642069642073656d2065676574206d6173736120756c74726963657320766976657272612e20416c697175616d206572617420766f6c75747061742e2044756973207669766572726120746f72746f7220696420616c697175657420706f7274612e20566976616d7573207665686963756c612073697420616d6574206f72636920696e206d6f6c65737469652e20416c697175616d206572617420766f6c75747061742e20566573746962756c756d2072686f6e6375732c2072697375732065752072757472756d206672696e67696c6c612c2073656d20697073756d2074656d7075732075726e612c207175697320747269737469717565206d6920647569206e6563206e6962682e20`

The user friendly message is implemented though, so the issue is probably only that the user unfriendly message is not hidden.

>> Probably there is some issue with the -l flag.

>> No, because you set the locktime to 1000, and 1000 means block 1000, not 1000 blocks in the future. Won't change this.

While `slimcoind` was on the block `984606` I've run `coin opreturn 4c6f72656d20697073756d20646f6c6f722073697420616d65742c20636f6e73656374657475722061646970697363696e6720656c69742c2073656420646f20656975736d6f642074656d706f7220696e6369646964756e74207574206c61626f726520657420646f6c6f7265206d61676e6120616c697175612e20557420656e696d206164206d696e696d2076656e69616d2c2071756973206e6f737472756420657865726369746174696f6e20756c6c616d636f206c61626f726973206e69736920757420616c697175697020657820656120636f6d6d6f646f20636f6e7365717561742e2044756973206175746520697275726520646f6c6f7220696e20726570726568656e646572697420696e -l 984706`.
The deriving transaction `82d4b506ef614bb43068f72d311b246fdf850af776547f79ed4af8b2a6158d10` was confirmed at block 984608.
My expectation was that it would be confirmed at the block 984708 or after that.

**Comment by buhtignew** [comment]
> The unfriendly error and some other unfriendly messages in the coin commands were fixed in the commit https://github.com/slimcoin-project/pacli/commit/e99e9ede9c7fba316643ccfc70c2c55b6aa89132.

Everything is fine on my end with this part.


> BTW it doesn't make much sense for me to offer the Locktime feature and then "disable it in all PeerAssets-created transactions by default".

That was what I was thinking as well.
However it's not that important at this stage we can keep it for the next version and disable the `-l` flag in the mean time, if possible.

**Comment by d5000** [comment]
I changed the folder structure in pacli and forgot some `__init__.py` files. (The problem was that at my side everything worked ... and I also thought these files were not longer necessary in newer Python 3 versions, but it seems I was wrong.)

Should be fixed with commit fed3ca9 (pypeerassets is not affected, there all of those files are present.)

**Comment by d5000** [comment]
Strange. I have installed pacli in a different python environment from github and got no issues.

Can you try to re-install pacli (see [manual](https://github.com/slimcoin-project/Slimcoin/wiki/PeerAssets:-dPoD-Tokens-Manual#installation) if you don't remember - uninstall pacli first with `pip uninstall pacli` from the folder where your pacli lives in)? I think pypeerassets reinstall is not necessary, nor is the generation of a new config file.

In the case it still doesn't work:

What is the content of the `pacli` subfolder? There should be folders like `extended`, `dex`, `blockexp`, `at` and `dt` which weren't present util about 5 commits ago. If they aren't there, something went wrong.
What is the python version and OS?

It's possible we had a a similar issue already earlier, but I don't remember exactly how it was solved.

**Comment by buhtignew** [comment]
Issue solved.

The `coin opreturn` works with the `-l` flag as well on my side.

Maybe it would make sense to edit the `-l` flag explanation in the `coin opreturn -h` from:
```
Specify a lock time.
```
into 
```
Specify a blockheight after which the OP_RETURN transaction should be sent.
```
Because with the default value of 0 the "lock time" concept looks more like "the number of blocks to delay".

If you don't agree, just close :-)
