### ISSUE TITLE
Suppressing KeyboardInterrupt error message?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#215]
I've seen that when I run `address cache mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh` for instance I can interrupt it anytime by pressing `CTRL+SHIFT+c` and the command just terminates.
But if I press the same key combination while the `address list` command is running I'm getting a long error message:
```
  File "~/.local/lib/python3.12/site-packages/pypeerassets/protocol.py", line 122, in p2th_address
    if self._p2th_address:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'Deck' object has no attribute '_p2th_address'. Did you mean: 'p2th_address'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 563, in list
    return ei.run_command(self.__list, advanced=advanced, keyring=keyring, coinbalances=coinbalances, labels=labels, full_labels=full_labels, no_labels=without_labels, only_labels=only_labels, named=named, quiet=quiet, p2th=p2th, network=blockchain, include_all=include_all, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 595, in __list
    excluded_addresses = eu.get_p2th()
                         ^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_utils.py", line 664, in get_p2th
    result.append(deck.p2th_address) # Deck P2TH addr.
                  ^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/protocol.py", line 125, in p2th_address
    self._p2th_address = Kutil(network=self.network,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/kutil.py", line 47, in __init__
    self._public_key = PublicKey.from_priv(self._private_key)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/btcpy/structs/crypto.py", line 133, in from_priv
    return priv.pub()
           ^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/btcpy/structs/crypto.py", line 71, in pub
    raw_pubkey = bytearray(SigningKey.from_string(self.key, curve=SECP256k1).get_verifying_key().to_string())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/ecdsa/keys.py", line 151, in from_string
    return klass.from_secret_exponent(secexp, curve, hashfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/ecdsa/keys.py", line 138, in from_secret_exponent
    pubkey_point = curve.generator*secexp
                   ~~~~~~~~~~~~~~~^~~~~~~
  File "~/.local/lib/python3.12/site-packages/ecdsa/ellipticcurve.py", line 133, in __mul__
    if ( e3 & i ) != 0 and ( e & i ) == 0: result = result + self
                                                    ~~~~~~~^~~~~~
  File "~/.local/lib/python3.12/site-packages/ecdsa/ellipticcurve.py", line 102, in __add__
    numbertheory.inverse_mod( other.__x - self.__x, p ) ) % p
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/ecdsa/numbertheory.py", line 195, in inverse_mod
    q, c, d = divmod( d, c ) + ( c, )
              ^^^^^^^^^^^^^^
KeyboardInterrupt
```
which is not that comfortable.
Would it make sense/be possible to suppress this error message?

**Comment by d5000** [comment]
Changed it this way: if a KeyboardInterrupt is done and was not catched inside a command function (like in `address cache`), the command will exit printing "Aborted.". Commit: 8cd4020

Does not need testing, can be closed.
