### ISSUE TITLE
token show with -f and -i flags error

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#216]
I've just run `token show johns_first_ATtoken -f -i` and got:
```
No entry or label was found matching the search string.
Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1022, in show
    return ei.run_command(self.__show, deckstr=_idstr, param=param, info=info, rawinfo=rawinfo, find=find, show_p2th=show_p2th, quiet=quiet, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1040, in __show
    deckinfo = eu.get_deckinfo(deckid, show_p2th)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_utils.py", line 161, in get_deckinfo
    d_dict = d.__dict__
             ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by d5000** [comment]
I catched the error in commit e811881.

The `-f` option searches for a string in the deck ID so there will be no result in this case because you used a label or global name. Simply omit the `-f` and it will be found.

`-f` is in this case an option I'll perhaps remove in the future because its usefulness is very limited, but for now it doesn't do harm and I don't remember if I had a specific use case in mind.

Can be closed, doesn't need testing.

**Comment by buhtignew** [comment]
I've run `token show a8b5b29  -f -i` and got:
```
Entries found with content a8b5b29:
[
    {
        'johns_first_ATtoken': 'ea7772ba8b5b297a35a50fac94431db5fc73731dfa7314dd53394d919ca4af58'
    }
]

Error: String a8b5b29 not found, no deck ID containing it.
```

**Comment by buhtignew** [comment]
>  I have removed the `-f` option from `deck show`

The option is still in the list of flags in `deck show -h` output.
Although it's basically ignored if trying to use.

> The deprecation warning seems to only appear in Python 3.12, my main version is 3.11. 

FYI, after the OS upgrade the warning disappeared.

**Comment by d5000** [comment]
> The option is still in the list of flags

True, removed the flag completely (will be pushed with next update). Can be closed now I think.

> FYI, after the OS upgrade the warning disappeared.

In one of my last updates I also applied the recommended way to solve the problem with the deprecated UTC timestamp issue, so it won't appear again on other OSses.
