### ISSUE TITLE
attoken send_coins error message

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#227]
My main address `myHPHhnncUaiFQGqN1FK2qFtwcfPE4Bkqc` has 0.03 tSLMs right now.
I've run ` attoken send_coins mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP 0.02 -f` and got the following error message:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 494, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_classes.py", line 251, in send_coins
    return ei.run_command(super()._create_tx, address_or_deck=address_or_deck, amount=amount, tx_fee=tx_fee, change=change, sign=sign, send=send, wait_for_confirmation=wait_for_confirmation, verify=verify, quiet=quiet, debug=debug, force=force, optimize=optimize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_classes.py", line 74, in _create_tx
    rawtx = au.create_simple_transaction(amount=dec_amount, dest_address=address, tx_fee=tx_fee, change_address=change_address, debug=debug)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_utils.py", line 28, in create_simple_transaction
    dtx.add_change_output(change_address)
  File "~/.local/lib/python3.12/site-packages/pypeerassets/at/mutable_transactions.py", line 105, in add_change_output
    self.add_p2pkh_output(address, sats=change_amount, output_index=output_index)
  File "~/.local/lib/python3.12/site-packages/pypeerassets/at/mutable_transactions.py", line 75, in add_p2pkh_output
    raise ValueError()
ValueError
pacli > attoken send_coins mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP 0.02 -f
Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 494, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_classes.py", line 251, in send_coins
    return ei.run_command(super()._create_tx, address_or_deck=address_or_deck, amount=amount, tx_fee=tx_fee, change=change, sign=sign, send=send, wait_for_confirmation=wait_for_confirmation, verify=verify, quiet=quiet, debug=debug, force=force, optimize=optimize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_classes.py", line 74, in _create_tx
    rawtx = au.create_simple_transaction(amount=dec_amount, dest_address=address, tx_fee=tx_fee, change_address=change_address, debug=debug)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_utils.py", line 28, in create_simple_transaction
    dtx.add_change_output(change_address)
  File "~/.local/lib/python3.12/site-packages/pypeerassets/at/mutable_transactions.py", line 105, in add_change_output
    self.add_p2pkh_output(address, sats=change_amount, output_index=output_index)
  File "~/.local/lib/python3.12/site-packages/pypeerassets/at/mutable_transactions.py", line 75, in add_p2pkh_output
    raise ValueError()
ValueError
```

**Comment by Coy326** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by d5000** [comment]
This was a small bug in pypeerassets (only appeared when the funds are insufficient to add a change amount). Fixed in pypeerassets commit 3573447.

I also fixed another small bug which can appear with tokens with a high number of decimals (>=30, for example the meme1338 token - ID: 37ca273030acde6e6e76c5cc2924a9c5b2045b164aaceb866270c28ee0e446b0) in f24813f.

BTW seems my nodes disconnected from yours. If your server is running I may have stranded on a fork.

**Comment by buhtignew** [comment]
This works, unfortunately my server is down so the test blockchain is stuck thus for the moment I'm not able to test some of the issues.
I've opened the ticket with the server's provider, hope to be able to solve soon.
