### ISSUE TITLE
Should we hide this error message provided with "card balances -c" ouptut?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#76]
I've tried to test `card balances` with `-c` flag.
Both `card balances -c` and `card balances -c -a` provides me the following output:
```
Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 446, in main
    fire.Fire({
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_classes.py", line 1153, in balances
    return ei.run_command(self.__balance, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_interface.py", line 33, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_classes.py", line 1202, in __balance
    deck_type = c.get_deck_type(category.lower()) if category is not None else None
                                ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'
```
The fact that my usage was wrong is quite clear to me so I'm wondering whether it make sense suppressing the error message in this case...

**Comment by d5000** [comment]
Catched the error properly in commit df47e41, see issue #27 . Can be closed.
